# Generated by Django 4.2.5 on 2023-09-09 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tematic',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='products.tematic'),
            preserve_default=False,
        ),
    ]
